name: CI to publish docker image to dockerhub registry

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build_image_and_deploy_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.username }}/public_pets:mock-service
