name: Docker Image creation and server running

on:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag public_pets:mock-service
    - name: Running docker container
      run: docker run -p 5555:5555 -d public_pets:mock-service