name: integration testing
on:
  workflow_call:
    secrets:
      username:
        required: true
    inputs:
      python_version:
        required: true
        type: number
  pull_request:
    paths:
      - '**.py'
    branches:
      - dev/**
  workflow_dispatch:

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
      - name: Running service
        run: |
            docker run -p 5555:5555 -d ${{ secrets.username }}/public_pets:mock-service
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest requests
      - name: Testing the code using integration_tests
        run: |
            pytest tests/integration_tests/