name: Integration testing
on:
  workflow_call:
    secrets:
      username:
        required: true
    inputs:
      python_version:
        required: true
        type: string
        default: '3.11'
  push:
    paths:
      - '**.py'

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
      - name: Building service image
        run: docker build -t public_pets:mock-service .
      - name: Running service
        run: docker run -p 5555:5555 -d public_pets:mock-service
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Testing the code using integration_tests
        run: |
          pytest tests/integration_tests/
