name: unit_testing
on:
  pull_request:
    paths:
      - '**.py'
    paths-ignore:
      - 'tests/**'
    branches:
      - dev/**
  workflow_call:

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
      - name: Testing the code using unit-tests
        run: |
            pytest tests/unit_tests/